--CRIAR A TABELA DE EMPRESA
CREATE TABLE EMPRESA(
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	RAZAOSOCIAL VARCHAR(150) NOT NULL,
	CNPJ VARCHAR(20) NOT NULL UNIQUE);

--INSERINDO EMPRESAS
INSERT INTO EMPRESA (ID, RAZAOSOCIAL, CNPJ) 
VALUES (NEWID(), 'EMPRESA A', '12.345.678/0001-90'),
	   (NEWID(), 'EMPRESA B', '98.765.432/0001-01')

--EXIBINDO OS REGISTROS DAS EMPRESA
SELECT * FROM EMPRESA;

-- CRIAR A TABELA DE FUNCIONARIO
CREATE TABLE FUNCIONARIO(
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL UNIQUE,
	MATRICULA VARCHAR(15) NOT NULL UNIQUE,
	DATAADMISSAO DATE NOT NULL,
	EMPRESAID UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (EMPRESAID) REFERENCES EMPRESA(ID));

